export const welcomeSubject = "You're on the list! A little hello from Little Red Writing Hood";
export const instagram = "https://www.instagram.com/littleredwritinghooddd/";
export const tiktok = "https://www.tiktok.com/@littleredwritinghooddd";
export function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
}
export function welcomeEmail(firstName: string) {
  const name = escapeHtml(firstName);
  const text = `Hi ${firstName},\n\nThank you for joining Little Red Writing Hood. Your signup is safely on the list, and I'm so happy you're here.\n\nThis is a little corner for snail mail, lovely paper finds and the joy of sending something thoughtful. I'll share occasional updates when there is something new to show you, from stationery ideas to plans for finding a pen pal.\n\nIn the meantime, come say hallo and discover cute mail, unboxings and other little finds.\n\nInstagram: ${instagram}\nTikTok: ${tiktok}\n\nThank you for being here from the beginning.\nLittle Red Writing Hood\n\nYou received this one-time welcome because this email address was used to sign up. If that wasn't you, or you'd like your signup removed, reply to this email.`;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Welcome to Little Red Writing Hood</title></head><body style="margin:0;background:#f4efe5;color:#403e35;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden">You're on the list. Come say hello and discover lovely little things.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4efe5"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="560" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;background:#fffdf6;border:1px solid #ded7c6"><tr><td style="height:10px;background:#a9b99c"></td></tr><tr><td style="padding:32px 32px 12px;text-align:center"><p style="font-size:11px;letter-spacing:3px;color:#8c312c">LITTLE RED WRITING HOOD</p><p style="color:#c6a851;font-size:28px;margin:20px 0">✦</p><h1 style="font-family:Georgia,serif;font-weight:normal;font-size:34px;line-height:1.2;color:#873730;margin:0">A little hello,<br>a lovely beginning.</h1></td></tr><tr><td style="padding:16px 32px 32px;font-size:15px;line-height:1.8"><p>Hi ${name},</p><p>Thank you for joining Little Red Writing Hood. Your signup is safely on the list, and I'm so happy you're here.</p><p>This is a little corner for snail mail, lovely paper finds and the joy of sending something thoughtful. I'll share occasional updates when there is something new to show you, from stationery ideas to plans for finding a pen pal.</p><p>In the meantime, come say hallo and discover cute mail, unboxings and other little finds.</p><table role="presentation" cellspacing="0" cellpadding="0" style="margin:24px 0"><tr><td style="background:#873730;border-radius:5px"><a href="${instagram}" style="display:inline-block;padding:12px 20px;color:#fff;text-decoration:none;font-size:14px">Find me on Instagram</a></td></tr></table><p><a href="${tiktok}" style="color:#476c83">Or join me on TikTok →</a></p><p style="margin-top:28px">Thank you for being here from the beginning.<br><strong style="color:#873730">Little Red Writing Hood</strong></p></td></tr><tr><td style="border-top:1px dashed #b9c9d1;padding:22px 32px;font-size:11px;line-height:1.6;color:#706d63">You received this one-time welcome because this email address was used to sign up. If that wasn't you, or you'd like your signup removed, reply to this email.</td></tr></table></td></tr></table></body></html>`;
  return {subject: welcomeSubject,html,text};
}
